src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @Gedmo\Tree(type="nested")
 * @ORM\Table(name="category")
 * use repository for handy tree functions
 * @ORM\Entity(repositoryClass="Gedmo\Tree\Entity\Repository\NestedTreeRepository")
 */
//* @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")

class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(length=64)
     */
    private $name;

    /**
     * @ORM\Column(length=64, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(length=256, nullable=true)
     */
    private $meta_description;

    /**
     * @Gedmo\TreeLeft
     * @ORM\Column(name="lft", type="integer")
     */
    private $lft;

    /**
     * @Gedmo\TreeLevel
     * @ORM\Column(name="lvl", type="integer")
     */
    private $lvl;

    /**
     * @Gedmo\TreeRight
     * @ORM\Column(name="rgt", type="integer")
     */
    private $rgt;

    /**
     * @Gedmo\TreeRoot
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(name="tree_root", referencedColumnName="id", onDelete="CASCADE")
     */
    private $root;

    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Category", mappedBy="parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $children;

    /**
     * One Product has Many Features.
     * @ORM\OneToMany(targetEntity="Product", mappedBy="category", indexBy="id")
     */
    private $products;

    /**
     * One Category has Many Filters.
     * @ORM\OneToMany(targetEntity="CategoryFilter", mappedBy="category", indexBy="id")
     */
    private $filters;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductGroup", mappedBy="category", orphanRemoval=true)
     */
    private $productGroups;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $singleName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pluralName;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->filters = new ArrayCollection();
        $this->children = new ArrayCollection();
        $this->productGroups = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Category
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return Category
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLft()
    {
        return $this->lft;
    }

    /**
     * @param mixed $lft
     * @return Category
     */
    public function setLft($lft)
    {
        $this->lft = $lft;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLvl()
    {
        return $this->lvl;
    }

    /**
     * @param mixed $lvl
     * @return Category
     */
    public function setLvl($lvl)
    {
        $this->lvl = $lvl;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getRgt()
    {
        return $this->rgt;
    }

    /**
     * @param mixed $rgt
     * @return Category
     */
    public function setRgt($rgt)
    {
        $this->rgt = $rgt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getRoot()
    {
        return $this->root;
    }

    /**
     * @param mixed $root
     * @return Category
     */
    public function setRoot($root)
    {
        $this->root = $root;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param mixed $parent
     * @return Category
     */
    public function setParent($parent)
    {
        $this->parent = $parent;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * @param mixed $children
     * @return Category
     */
    public function setChildren($children)
    {
        $this->children = $children;
        return $this;
    }

    /**
     * @return mixed
     */
    public function isActive()
    {
        return $this->isActive;
    }

    /**
     * @param bool $isActive
     * @return Category
     */
    public function setIsActive(bool $isActive): Category
    {
        $this->isActive = $isActive;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getMetaDescription()
    {
        return $this->meta_description;
    }

    /**
     * @param mixed $meta_description
     * @return Category
     */
    public function setMetaDescription($meta_description)
    {
        $this->meta_description = $meta_description;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getProducts()
    {
        return $this->products;
    }

    public function getFilters()
    {
        return $this->filters;
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function forTree()
    {
        return sprintf('%s %s', str_repeat('--', $this->getLvl()), $this->getName());
    }

    /**
     * @return Collection|ProductGroup[]
     */
    public function getProductGroups(): Collection
    {
        return $this->productGroups;
    }

    public function addProductGroup(ProductGroup $productGroup): self
    {
        if (!$this->productGroups->contains($productGroup)) {
            $this->productGroups[] = $productGroup;
            $productGroup->setCategory($this);
        }

        return $this;
    }

    public function removeProductGroup(ProductGroup $productGroup): self
    {
        if ($this->productGroups->contains($productGroup)) {
            $this->productGroups->removeElement($productGroup);
            // set the owning side to null (unless already changed)
            if ($productGroup->getCategory() === $this) {
                $productGroup->setCategory(null);
            }
        }

        return $this;
    }

    public function getSingleName(): ?string
    {
        return $this->singleName;
    }

    public function setSingleName(?string $singleName): self
    {
        $this->singleName = $singleName;

        return $this;
    }

    public function getPluralName(): ?string
    {
        return $this->pluralName;
    }

    public function setPluralName(?string $pluralName): self
    {
        $this->pluralName = $pluralName;

        return $this;
    }

}

src/Controller/Frontend/CatalogController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\Category;
use App\Filter\ProductFilter;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use App\Repository\VendorRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Knp\Component\Pager\Paginator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class CatalogController extends AbstractController
{
    use FrontendTraitController;

    CONST ROWS_PER_PAGE = 12;
    CONST MODEL = 'product';
    CONST ENTITY_NAME = 'Product';
    CONST NS_ENTITY_NAME = 'App:Product';

    /**
     * Генерация меню в каталожном LAYOUT
     * @return Response
     */
    public function categoriesTreeMenu()
    {
        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $products_count = $em->createQueryBuilder()
            ->select('c.id, COUNT(p.id) as prod_cnt')
            ->from('App:Category', 'c')
            ->innerJoin('c.products', 'p')
            ->where('p.isActive = :isActive')
            ->setParameter('isActive', true)
            ->groupBy('c.id')
            ->getQuery()
            ->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);

        $category_product_counts = [];

        foreach ($products_count as $item) {
            $category_product_counts[$item['id']] = $item['prod_cnt'];
        }

        $repo = $em->getRepository('App:Category');
        $arrayTree = $repo->childrenHierarchy();

        $tree_arr = [];
        foreach ($arrayTree as $index => $node) {
            if (false === $node['isActive']) {
                continue;
            }
            $tree_arr[$index] = [
                'name' => $node['name'], // . $node['id'],
                'href' => $url = $this->generateUrl("category_show", array(
                        "slug" => $node['slug'])
                ),
            ];
            $tree_arr[$index]['products_cnt'] = isset($category_product_counts[$node['id']]) ? $category_product_counts[$node['id']] : '';
            if (is_array($node['__children']) && sizeof($node['__children'])) {
                $tree_arr[$index]['children'] = $this->renderSubtree($node['__children'], $category_product_counts);
            }
        }

        return $this->render('common/tree_as_menu.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.project_dir') . '/..') . DIRECTORY_SEPARATOR,
            'array_tree' => $arrayTree,
            'tree_arr' => $tree_arr,
            'products_count' => $products_count,
        ]);
    }

    private function renderSubtree($arrayTree, $category_product_counts)
    {
        $tree_arr = [];
        foreach ($arrayTree as $index => $node) {
            $tree_arr[] = [
                'name' => $node['name'], // . $node['id'],
                'href' => $url = $this->generateUrl("category_show", array(
                        "slug" => $node['slug'])
                ),
            ];
            $tree_arr[$index]['products_cnt'] = isset($category_product_counts[$node['id']]) ? $category_product_counts[$node['id']] : '';
            if (is_array($node['__children']) && sizeof($node['__children'])) {
                $tree_arr[$index]['children'] = $this->renderSubtree($node['__children'], $category_product_counts);
            }
        }

        return $tree_arr;
    }

    public function buildNewQuery(ProductRepository $repository, Request $request, Category $category): QueryBuilder
    {
        $checkedVendors = $request->query->get('vendor', []);
        $categoryFilters = $request->query->get('cfilter', []);

        $queryBuilder = $repository->createQueryBuilder('p')
            ->innerJoin('p.vendor', 'v')
            ->innerJoin('p.category', 'c')
            ->leftJoin('p.productFilterValues', 'pfv')
            ->where('p.isActive = true')
            ->andWhere('p.category = :category')
            ->setParameter('category', $category->getId())
        ;

        if ([] !== $checkedVendors) {
            $queryBuilder->andWhere('p.vendor IN (:vendors)')
                ->setParameter('vendors', $checkedVendors);
        }

        if ([] !== $categoryFilters) {
//            foreach ($categoryFilters as $cfId => $categoryFilter) {
//                $queryBuilder->andWhere("pfv.category_filter_value_id IN (:filter_values_{$cfId})")
//                    ->setParameter("filter_values_{$cfId}", array_values($categoryFilter));
//            }
            
            $currentFilters = [];
            array_walk_recursive($categoryFilters, function ($value) use (&$currentFilters) {
                $currentFilters[] = $value;
            });

            $queryBuilder->andWhere("pfv.categoryFilterValue_id IN (:filter_values)")
                ->setParameter("filter_values", $currentFilters);
            $queryBuilder->groupBy('p.id');
            $queryBuilder->having('COUNT(pfv.id) = ' . count($categoryFilters));
        }

        return $queryBuilder;
    }

    private function getFilteredProductIds(QueryBuilder $query)
    {
        $rows = $query->select('DISTINCT p.id')
            ->getQuery()->getResult()
        ;

        $ids = array_map(function ($row) {
            return $row['id'];
        }, $rows);

        return array_values($ids);
    }

    private function getQueryForPager(ProductRepository $repository,
                                      QueryBuilder $queryBuilder, array $ids): Query
    {

        $queryBuilder = $repository->createQueryBuilder('p')
            ->innerJoin('p.vendor', 'v')
            ->where('p.isActive = true')
            ->andWhere('p.id IN (:ids)')
            ->setParameter('ids', $ids)
        ;

        return $queryBuilder->getQuery();
    }

    /**
     * Displays a form to edit an existing product entity.
     *
     * @Route("/category/{slug}", name="category_show")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function showCategory(Request $request,
                                 SessionInterface $session,
                                 CategoryRepository $repository,
                                 ProductRepository $productRepository,
                                 VendorRepository $vendorRepository,
                                 string $slug)
    {
        /** @var Category $category */
        $category = $repository->findOneBy(['slug' => $slug]);
        if (!$category) {
            throw new NotFoundHttpException();
        }

        $parentCategory = $category->getParent();

        // add to session filter category
        $session_filters = $session->get('filters', array());
        $filter = @$session_filters[self::MODEL];

        $checkedVendors = $request->query->get('vendor', []);

        if ([] !== $checkedVendors) {
            $filter['vendor'] = $checkedVendors;
        }

        $filter['category'] = $category->getId();

        /** @var QueryBuilder $query */
        $queryBuilder = $this->buildNewQuery($productRepository, $request, $category);

        $productIds = $this->getFilteredProductIds($queryBuilder);

        $query = $this->getQueryForPager($productRepository, $queryBuilder, $productIds);

        $pagination = $this->paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            self::ROWS_PER_PAGE
        );

        $categoryVendors = $vendorRepository->getCategoryVendors($category);
        $cfilters = $request->query->get('cfilter', []);
        $currentFilters = [];
        array_walk_recursive($cfilters, function ($value) use (&$currentFilters) {
            $currentFilters[] = $value;
        });

        $page = $request->query->get('page', false);
        $sort = $request->query->get('sort', 'product.name');

        $isPager = (false !== $page OR false !== $sort) ? true : false;

        return $this->render('catalog/products.html.twig', array(
            'category' => $category,
            'categoryVendors' => $categoryVendors,
            'checkedVendors' => $checkedVendors,
            'parentCategory' => $parentCategory,
            'pagination' => $pagination,
            'cfilters' => $currentFilters,
            'current_filters' => false, // todo: remove it
            'model' => self::MODEL,
            'entity_name' => self::ENTITY_NAME,
            'slug' => $slug,
            'isPager' => $isPager,

            'list_fields' => [
                'a.name' => [
                    'title' => 'Name',
                    'row_field' => 'name',
                    'sorting_field' => 'product.name',
                    'sortable' => true,
                ],
                'a.price' => [
                    'title' => 'Price',
                    'row_field' => 'price',
                    'sorting_field' => 'product.price',
                    'sortable' => true,
                ],

            ]
        ));

//        $page = $request->query->get('page', 1);
//
//        // todo: wrap in try/catch
//
//        $em = $this->getDoctrine()->getManager();
//
//        /** @var Category $category */
//        $category = $em->getRepository(Category::class)->findOneBy(['slug' => $slug]);
//
//        if (!$category) {
//            throw new NotFoundHttpException();
//        }

//        $product_filter = new ProductFilter($request, $slug);
//        $price_from = $product_filter->getPriceFrom();
//        $price_to = $product_filter->getPriceTo();
//        $products = $em->getRepository('App:Product')->getPageFiltered($product_filter);

templates/themes/forel/catalog/products.html.twig
{% extends 'themes/forel/layout.html.twig' %}

{% block title %}{{ (parentCategory is not null ? parentCategory.name ~ ' ' : '') ~ category.name }}{% endblock %}

{% block meta_description %}{{ category.metaDescription }}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <i class="fa fa-dashboard"></i> <a href="{{ path('homepage') }}"> Главная</a>
        </li>
        {% if parentCategory is not null %}
            <li class="breadcrumb-item">
                <i class=""></i> {{ parentCategory.name }}
            </li>
        {% endif %}
        <li class="breadcrumb-item active">
            <i class=""></i> {{ category.name }}
        </li>
    </ol>
{% endblock %}

{% block body %}

    {% include 'themes/forel/common/flashes.html.twig' %}

    <div class="card mb-2 box-shadow">
        <form action="{{ path('category_show', {'slug': category.slug}) }}" method="get">
            <div class="card-body">
                <div class="row">
                    {% if categoryVendors|length %}
                        <div class="col-4">
                            <b>Производитель</b>
                            <ul class="list-unstyled">
                            {% for vendor in categoryVendors %}
                                <li><input type="checkbox" id="vendor_{{ vendor.id }}"
                                           {{ vendor.id in checkedVendors ? 'checked' : '' }}
                                           name="vendor[]" value="{{ vendor.id }}">
                                    <label for="vendor_{{ vendor.id }}">{{ vendor.name }}</label></li>
                            {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% if category.filters|length %}
                        {% for filter in category.filters %}
                            <div class="col-4">
                                <b>{{ filter }}</b>
                                <ul class="list-unstyled">
                                {% for filterValue in filter.filterValues %}
                                    <li><input type="checkbox" id="cfilter_{{ filterValue.id }}"
                                               {{ filterValue.id in cfilters ? 'checked' : '' }}
                                               name="cfilter[{{ filter.id }}][]" value="{{ filterValue.id }}">
                                        <label for="cfilter_{{ filterValue.id }}">{{ filterValue }}</label></li>
                                {% endfor %}
                                </ul>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">применить</button>
                <button type="button" class="btn btn-secondary" id="resetFilter">сбросить</button>
            </div>
        </form>
    </div>
    <div class="card mb-2 box-shadow">
        <div class="card-body">
        Сортировать по:
            {% set direction = pagination.getDirection() %}
            {{ knp_pagination_sortable(pagination, 'названию', 'p.name') }}
            {% if pagination.isSorted('p.name') %}<i class="fa fa-arrow-{{ direction == 'asc' ? 'down' : 'up' }}"></i>{% endif %}
            |
            {{ knp_pagination_sortable(pagination, 'цене', 'p.price') }}
            {% if pagination.isSorted('p.price') %}<i class="fa fa-arrow-{{ direction == 'asc' ? 'down' : 'up' }}"></i>{% endif %}
        </div>
    </div>
    <div class="row text-center">
        {% for index, row in pagination %}
            <div class="col-sm-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal"><a
                            class="alert-link"
                            href="{{ path('product_view', {'categorySlug': category.slug, 'productSlug': row.slug}) }}">
                                {{ row.vendor.name }} - {{ row.name }}</a></h5>
                    </div>
                    <div class="card-body">
                        {% if row.pic %}
                            <a data-fancybox="gallery" target="_blank" href="{{ asset('/uploads/pics/' ~ row.pic) }}"><img
                                        src="{{ asset('/uploads/pics/' ~ row.pic) | imagine_filter('thumb_square_160') }}" /></a>
                        {% else %}
                            ---
                        {% endif %}

                        <h1 class="card-title pricing-card-title product_price">{{ row.price }} ₽</h1>

                        <div class="text-center">
                            <span class="badge badge-{{ row.statusAsCssClass }}">{{ row.statusRus }}</span>
                        </div>

                        {% if row.isAvailableToOrder %}
                            <a href="{{ path('add_to_cart', {'id': row.id}) }}"
                               class="btn btn-lg btn-block btn-primary text-white"><i
                                        class="fa fa-cart-plus"></i> В корзину</a>
                        {% else %}
                            <a href="javascript:;"
                               class="btn btn-lg btn-block btn-secondary text-white"><i
                                        class="fa fa-info-circle"></i> {{ row.statusRus }}</a>
                        {% endif %}

                        <a href="{{ path('product_view', {'categorySlug': category.slug, 'productSlug': row.slug}) }}"
                           class="btn btn-lg btn-block btn-success text-white"><i
                                    class="fa fa-search"></i> Просмотр</a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


    {# display navigation #}
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
        <div class="count">
            Количество записей: {{ pagination.getTotalItemCount }}
        </div>
    </div>

{% endblock %}

{% block filter_scripts %}
    <script>
        $( document ).ready(function() {
            $('#resetFilter').on('click', function () {
                document.location = '{{ path('category_show', {'slug': category.slug}) }}';
            })
        })
    </script>
{% endblock %}

{% block filter_form %}
    {% include 'admin/common/filter_form.html.twig' with {'filter_form': filter_form} %}
{% endblock %}